name: ming_map
description: "A map and loction power by Baidu Map"
version: 0.0.1
homepage: https://www.yfmingo.cn/
publish_to: 'none'  # 这行是关键！none 不发布大片pubdev。可以使用path路径

environment:
  sdk: ^3.10.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
#  dio_log:
#    git:
#      url: https://github.com/yfming93/dio_log.git
#      ref: develop
#  dio_log:
#    path: /Users/mingo/allRepos/all_kit/dio_log/
#  app_log:
#    path: /Users/mingo/allRepos/all_kit/app_log/
  app_log:
    git:
      url: https://github.com/DartKit/app_log.git
  app_kit:
    git:
      url: https://github.com/DartKit/app_kit.git
#  app_kit:
#    path: /Users/mingo/allRepos/all_kit/app_kit/
  get: 4.7.3
  flutter_screenutil: ^5.9.3
  permission_handler: 12.0.1
  url_launcher: 6.3.2
  visibility_detector: ^0.4.0+2 #视图是否可见

  flutter_bmflocation: 3.8.3
  flutter_baidu_mapapi_base: 3.9.5
  flutter_baidu_mapapi_map: 3.9.5
  flutter_baidu_mapapi_utils: 3.9.5

dependency_overrides:
  geolocator: 14.0.2 #检测通知栏是否开启了定位服务
  package_info_plus: 9.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.10.4
  flutter_lints: ^6.0.0
  assets_scanner_plus: ^3.2.0 #dart run build_runner build

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - lib/ast/
    - lib/ast/file/
    - lib/ast/images/

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An images asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
